export const AppError = {
  USER_EXIST: 'Користувач із цією електронною адресою вже існує.',
  COURSE_EXIST: 'курс вже існує.',
  USER_NOT_EXIST: 'Користувача з цією електронною адресою не існує.',
  WRONG_DATA: 'Невірні дані',
  PRODUCT_EXIST: 'Продукт із цією назвою вже існує.',
  PRODUCT_NOT_EXIST: 'Продукта з таким ідентифікатором не існує.',
  VOLUME_PRICE_MISMATCH_ERROR:
    'Кількість значень обсягу не відповідає кількості цін.',
  WRONG_ROLE: 'У вас немає прав адміністратора',
  PRODUCTS_NOT_EXIST: 'Продукти не існують.',
  PRODUCT_ID_NOT_EXIST: 'Продуктів із цим ідентифікатором не існує.',
  CART_NOT_EXIST: 'Кошик не існує.',
  USER_NOT_HAVE_CART: 'У цього користувача немає кошика.',
  CART_NOT_FOUND: 'Кошик не знайдено',
  WRONG_ADDED_CART: 'Щось пішло не так, кошик не був доданий',
  WRONG_ADDED_CART_PRODUCT: 'Щось пішло не так, продукт кошика не був доданий',
  PRICE_IS_EMPTY: 'Ціна порожня',
  PRICE_NOT_EXIST: 'Ціни із цим ідентифікатором не існує',
  PRICE_EXIST: 'Ціна із цією назвою вже існує.',
  COST_PRICE_EMPTY: 'Назва та ціна повинні бути не порожніми',
  TEAMMATE_EXIST: 'Користувач із цією назвою вже існує.',
  TEAMMATE__NAME_NOT_EXIST: 'Користувача із цією назвою не існує.',
  TEAMMATE_ID_NOT_EXIST: 'Користувача з таким ідентифікатором не існує.',
  COURSE_ID_NOT_EXIST: 'Курс з таким ідентифікатором не існує.',
  TEAMMATE_NOT_EXIST: 'Працівники не існують.',
  COURSE_NOT_EXIST: 'Курс не існує.',
};
